//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arengo6_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesGallery
    {
        public int ID { get; set; }
        public string ImageName { get; set; }
        public string url { get; set; }
        public Nullable<int> ImageType { get; set; }
    }
}
